### ISSUE TITLE
AFNO implementation differs from paper 

### ISSUE THREAD

**Issue by Alexszeni** [NVlabs/FourCastNet#5]
Hi,

In your paper, you define the AFNO layer such that 

   bias = x
   x = RFFT2(x)
   x = x.reshape(b, h, w//2+1, k, d/k)
   x = BlockMLP(x)
   x = x.reshape(b, h, w//2+1, d)
   x = SoftShrink(x)
   x = IRFFT2(x)
   return x + bias 

such that the MLP happens between the FFT and IFFT.
However, in your codebase, it's 

      residual = x
      x = self.norm1(x)
      x = self.filter(x) 

      if self.double_skip:
          x = x + residual
          residual = x

      x = self.norm2(x)
      x = self.mlp(x)
      x = self.drop_path(x)
      x = x + residual 

Such that the MLP happens after the IFFT. Am I missing something?

**Comment by xswang-ai** [comment]
Hi, 
 I've also noticed the difference between the implementations. I believe you mean the truncation part here https://github.com/NVlabs/FourCastNet/blob/93360c1720a9f97aabf970689f21c9fad8737788/networks/afnonet.py#L79

Which kept the kept_modes low frequencies in the last dimension (same as the original AFNO paper),  and some mid range frequencies from [total_modes - kept_modes to total_modes + kept_modes] in the second last dimension (whereas the original paper kept all the modes)

I am assuming the authors want to improve efficiency and  ChatGPTs  provided some justification of doing so.
* Preserving Key Frequency Bands
Instead of just taking low frequencies, this method keeps an important band of frequencies symmetrically around total_modes.
This helps retain a mix of low-to-mid frequencies, which may be more useful in models like Fourier Neural Operators (FNOs).
* More Flexible Representation
In some applications (e.g., PDE solvers, turbulence modeling, or fluid dynamics), high-frequency components may contain useful structural information.
Instead of filtering only low frequencies, this keeps a balanced set of frequencies.
